#!/usr/bin/env bash
# File       : format_code
# Created    : Thu Nov 16 2023 09:22:20 (+0100)
# Author     : Fabian Wermelinger
# Description: Project wide code formatting tool (requires clang-format)
# Copyright (c) 2023 CCFNUM, Lucerne University of Applied Sciences and Arts.
# SPDX-License-Identifier: BSD-3-Clause

SOURCE='\.\./\.\./src/.*\.(c|cpp|C|h|hpp|H)'
EXCLUDE='../../src/solver/*'

# format in-place
find ../.. \
    -regextype 'egrep' \
    -regex "${SOURCE}" \
    -not -path "${EXCLUDE}" \
    -print0 | \
    xargs -0 -n12 -P$(nproc) clang-format -style=file -i "$@"
