name: Release tarball with submodules

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-release-tarball:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo + submodules
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive

      - name: Extract tag name
        id: vars
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create release (if not exists)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release view "${{ steps.vars.outputs.tag }}" \
          || gh release create "${{ steps.vars.outputs.tag }}" \
               --title "${{ steps.vars.outputs.tag }}" \
               --notes "Auto release for ${{ steps.vars.outputs.tag }}"

      - name: Build tar.gz including submodules
        run: |
          repo="${{ github.event.repository.name }}"
          version="${{ steps.vars.outputs.tag }}"
          dirname="${repo}-${version}"

          l="./src/solver"
          v="$(git -C ${l} tag --list --sort=-v:refname v* --merged | head -n1 | sed 's/v-\?//')"
          if [ -f "${l}/CMakeLists.txt" ]; then
              sed -i "s/#\\s*%GIT_TAG%\\s*\$/set(GIT_DESCRIBE_VERSION ${v})/" "${l}/CMakeLists.txt"
              sed -i '/^\s*#\s*%EXTERNAL_REPLACE_START%/,/^\s*#\s*%EXTERNAL_REPLACE_END%/d' "${l}/CMakeLists.txt"
          else
              echo "${l}/CMakeLists.txt does not exist for patching version ${v}"
              exit 1
          fi

          mkdir -p "${dirname}"
          rsync -a \
            --exclude ".git" \
            --exclude ".github" \
            --exclude ".gitmodules" \
            --exclude "${dirname}" \
            ./ "${dirname}/"

          tar -cJf "${dirname}.tar.xz" "${dirname}"
          tar -czf "${dirname}.tar.gz" "${dirname}"
          zip -qr "${dirname}.zip" "${dirname}"
          sha256sum ./*.tar.* ./*.zip >"${dirname}_checksums.txt"

      - name: Upload tarball to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload "${{ steps.vars.outputs.tag }}" ./*.tar.* ./*.zip ./*_checksums.txt --clobber
